blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.blog_home, name='blog_home'),
	path('<int:blog_id>', views.detail, name='detail'),

]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio_app import views

urlpatterns = [
	path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class MyBlog(models.Model):
	title = models.CharField(max_length= 50)
	description = models.TextField(max_length=500000)
	date = models.DateTimeField(auto_now= False, auto_now_add= False)

	def __str__(self):
		return self.title

portfolio_app/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
	title = models.CharField(max_length= 50)
	description = models.CharField(max_length= 250)
	image = models.ImageField(upload_to= 'portfolio_app/images/')
	url = models.URLField(blank= True)


	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import MyBlog

# Create your views here.
def blog_home(request):
	blogs = MyBlog.objects.order_by('-date')
	return render(request, 'blog/blog_home.html', {'blogs':blogs})

def detail(request, blog_id):
	blog =  get_object_or_404(MyBlog, pk=blog_id)
	return render(request, 'blog/detail.html', {'blog':blog})

portfolio_app/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
	projects = Project.objects.all() 
	return render(request,'portfolio_app/home.html', {'projects':projects})

blog/templates/blog/blog_home.html
{% extends 'portfolio_app/base.html' %}


{% block content %}

<div class="container-md text-center">
<h2 class="alert alert-primary">Aniket has written {{ blogs.count }} Blog{{ blogs.count|pluralize }}</h2>
</div>
{% for blog in blogs %}

<div class='col-12 col-md-10 mb-3 mx-auto'>
<div class="card bg-dark text-light">
<div class="card-body">
<a href="{% url 'blog:detail' blog.id %}"><h2 class="card-title">{{ blog.title }}</h2></a>
<p class="card-text">{{ blog.date|date:'M d Y' }}</p>
<p class="card-text">{{ blog.description|truncatechars:100 }}</p>

</div></div></div>

{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio_app/base.html' %}

{% block content %}

<div class="container" id="hometext">
<h2 class="text-center font-weight-bolder text-primary" id="blogdetailtitle">{{ blog.title }}</h2><br>
<p class="text-center">--{{ blog.date|date:'D d M Y' }}--<br>--{{ blog.date|time:"H:i" }}--</p><br>
<p class="text-center">{{ blog.description|linebreaks }}</p>
</div>

{% endblock %}

portfolio_app/templates/portfolio_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio_app/custom.css' %}">

    <title>Portfolio</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'portfolio_app/logo.jpg' %}" sizes="16x16">
  </head>
  <body>
  <div class="container-fluid">
  <header>
    <nav>
    <div class="navigation_bar"> 
    <a href="{% url 'home' %}">
    <img src="{% static 'portfolio_app/logo.jpg' %}" class="navimg" height="40" width="40">
    </a>
    <a href="{% url 'home' %}" class="navcon">Aniket Raj</a>
    <a href="{% static 'portfolio_app/resume1.pdf' %}" class="navcon">Resume</a>
    <a href="https://github.com/Aniket1317" class="navcon" target="_blank">Github</a>
    <a href="https://linkedin.com/in/aniket-raj-51b05b183" class="navcon" target="_blank">LinkedIn</a>
    <a href="{% url 'blog:blog_home' %}" class="badge badge-dark navcont">BLOG</a>
    </div>
    </nav>
  </header>
  </div>

      <div class='container-fluid'>
         {% block content %}
            {% endblock %}
      </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

portfolio_app/templates/portfolio_app/home.html
{% extends 'portfolio_app/base.html' %}
{% load static %}

{% block content %}

<div class="container" style="width: 30rem; ">

	<img class="rounded mx-auto d-block" src="{% static 'portfolio_app/ar.jpg' %}" height="400" width="450"><br>
	<div class="card-body">
	<h3 class="text-center font-weight-bold font-italic">Aniket Raj is a student. He is doing B.Tech in the field of Computer Science and Communication Engineering in KIIT University.</h3>
	</div>

</div></div><br><br>

<div class="p-3 mb-2 bg-secondary">
<div class="container">
<div class="row">

	{% for project in projects %}
	<div class="col-md-4">
	<div class="card mb-4" style="width: 18rem;" >
		<img src="{{ project.image.url }}" height="200">
		<div class="card-body">
		<h2 class="col-pl-3">{{ project.title }}</h2>
		<p>{{ project.description|truncatechars:100 }}</p>
		

		{% if project.url %}
			<br><a href="{{ project.url }}" class="btn btn-primary">View</a>
		{% endif %}
		</div>
	</div>
	</div>
	{% endfor %}

</div>
</div>
{% endblock %}